### PR TITLE
[REF] Clean up durations

### PR DESCRIPTION
**Pull request by tsalo**

### CODE REVIEW

**Comment by tsalo** [comment]
@adamkimbler would you mind reviewing and merging?

**Comment by adamkimbler** [comment]
@tsalo Everything looks good, but can we get some text for the exception raised if `num_type` isn't `analog` or `numeric`?

**Review by akimbler — CHANGES_REQUESTED** [review]
@tsalo Everything looks good, but can we get some text for the exception raised if `num_type` isn't `analog` or `numeric`?

**Comment by tsalo** [comment]
Should be good now.

**Review by akimbler — APPROVED** [review]

**Pull request merged**
